### PR TITLE
add pycon2021 landing page location

### PR DESCRIPTION
**Pull request by Maliaotw**
添加pycon2021 landing page的規則，部署前須先啟動pycontw-2021容器
https://github.com/pycontw/landing-page-2021/pull/1

### CODE REVIEW

**Comment by mattwang44** [comment]
[[Epic] Landing Page](https://trello.com/c/YLvopA2u/1-epic-landing-page)

**Comment by Maliaotw** [comment]
修改Proxy pass到Cloud Storage位置。

**Comment by mattwang44** [comment]
resolve conflict with #3

**Review by mattwang44 — APPROVED** [review]
LGTM

**Pull request merged**
